apex-base svnserve

diff --git a/bin/base-svnserve b/bin/base-svnserve
--- a/bin/base-svnserve
+++ b/bin/base-svnserve
@@ -1,25 +1,58 @@
 #!/bin/bash
 
-# 20161118, jtingiris
+# 20210124, joseph.tingiris@gmail.com
 
-Base_Repo_Dir="/var/svn/repo/base"
+Base_Dirs=(/apex /base)
+for Base_Dir in ${Base_Dirs[@]}; do
+    for Base_Prefix in apex base; do
+        Base_SvnServe_Dir="${Base_Dir}/etc/${Base_Prefix}-svnserve-dir"
+        #echo "Base_SvnServe_Dir=${Base_SvnServe_Dir} 1"
+        if [ -f "${Base_SvnServe_Dir}" ]; then
+            Base_Repo_Dir=$(head -1 "${Base_SvnServe_Dir}")
+            if [ -d "${Base_Repo_Dir}" ]; then
+                break
+            else
+                unset Base_Repo_Dir
+            fi
+        fi
+        if [ ${#Base_Repo_Dir} -gt 0 ]; then
+            break
+        fi
+    done
+done
+
+if [ ${#Base_Repo_Dir} -eq 0 ]; then
+    Base_Prefix="base"
+    Base_Repo_Dir="/var/svn/repo/base"
+fi
+
+if [ ! -d "${Base_Repo_Dir}" ]; then
+    echo "${Base_Repo_Dir} directory not found"
+    exit
+fi
+
 Base_Repo_Log="/var/log/base-svnserve.log"
 
-if [ "$Base_User" == "" ]; then
-    if [ "$Base_User" == "" ]; then
-        Base_User=$USER
+if [ "${Base_User}" == "" ]; then
+    Base_User="${Apex_User}"
+fi
+
+if [ "${Base_User}" == "" ]; then
+    if [ "${Base_User}" == "" ]; then
+        Base_User=${USER}
     fi
-    if [ "$Base_User" == "" ]; then
-        Base_User=$LOGNAME
+
+    if [ "${Base_User}" == "" ]; then
+        Base_User=${LOGNAME}
     fi
-    if [ "$Base_User" == "root" ]; then
-        if [ "$SSH_CLIENT" != "" ]; then
-            Base_User="root@$SSH_CLIENT"
-        else
-            Base_User="root@$HOSTNAME"
-        fi
-    fi  
-    if [ "$Base_User" == "" ]; then
+
+    if [ "${SSH_CLIENT}" != "" ]; then
+        Base_User+="@${SSH_CLIENT}"
+    else
+        Base_User+="@${HOSTNAME}"
+    fi
+
+    if [ "${Base_User}" == "" ]; then
         Base_User="anonymous"
     fi
 fi
@@ -28,20 +61,15 @@ umask 002 # 660
 
 PATH=/bin:/usr/bin:/sbin:/usr/sbin
 
-# call the 'real' svnserve, also passing in the default repo location
-/usr/bin/svnserve -t -r "$Base_Repo_Dir" --tunnel-user="$Base_User" \
+/usr/bin/svnserve -t -r "${Base_Repo_Dir}" --tunnel-user="${Base_User}" \
     --memory-cache-size 1024 \
     --cache-txdeltas yes \
     --cache-fulltexts yes
 
-# if svnserve changes the group ownership to anything other than apache, change it back
-if [ ! -f "$Base_Repo_Log" ]; then
-    touch "$Base_Repo_Log"
-    touch "$Base_Repo_Log"
-    chgrp apache "$Base_Repo_Log"
-    chmod 660 "$Base_Repo_Log"
+if [ ! -f "${Base_Repo_Log}" ]; then
+    touch "${Base_Repo_Log}"
 fi
 
-if [ -w "$Apex_Repo_Log" ]; then
-    echo "`date`: $USER : $SSH_CLIENT : $?" >> "$Base_Repo_Log"
+if [ -w "${Base_Repo_Log}" ]; then
+    echo "$(date): ${Base_User} : $?" >> "${Base_Repo_Log}"
 fi
